name: LafAdmin
appid: cjjd2h
invokeUrl: https://cjjd2h.xooio.cn
function:
  debugTokenExpire: 1688278057
storage:
  endpoint: https://oss.xooio.cn
  accessKeyId: OZWBOMPWOAG616P9U9S4
  accessKeySecret: WvBN5iFUbFQ49pcyeh4gOwHBam0FvlXdQ3rJQ34L
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJPWldCT01QV09BRzYxNlA5VTlTNCIsImV4cCI6MTY4ODI3ODA1NywicGFyZW50IjoiY2pqZDJoIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.6q-0jjWZ4Eh6Lh-RAdk437sVQQL03k8ioZXguntogfPoPTLs2aRX_655L60Emd9Si2yTJ3AkhCM8z6-rhFMn9w
  expire: 1688278057
