name: LafAdmin
appid: cjjd2h
invokeUrl: https://cjjd2h.xooio.cn
function:
  developToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBpZCI6ImNqamQyaCIsInR5cGUiOiJkZXZlbG9wIiwiZXhwIjoxNjg5OTA2MzY0LCJpYXQiOjE2ODkzMDE1NjR9.TdLkI5wgVEtBSyPNRVdmqqAtCRI20b3HinjppBgv24A
  developTokenExpire: 1689906365
storage:
  endpoint: https://oss.xooio.cn
  accessKeyId: C10O81XBZ4T96BX03EHM
  accessKeySecret: byUBqnHZEKn+R04gld9lpi9B+IaoKIfTFJuW1d+L
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJDMTBPODFYQlo0VDk2QlgwM0VITSIsImV4cCI6MTY4OTkwNjM2NCwicGFyZW50IjoiY2pqZDJoIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.mi1ep5D_1lm-Cj1gEdGuANCTdH74mP8u2lhcN7FofsFDCdDQZ1i4OkkiJN-9sT8YHtPnxPgD3q5X1uXPrcpT7Q
  expire: 1689906365
