name: LafAdmin
appid: cjjd2h
invokeUrl: https://cjjd2h.xooio.cn
function:
  debugTokenExpire: 1689062463
storage:
  endpoint: https://oss.xooio.cn
  accessKeyId: PTN3XTLDR92BBNNOM1B1
  accessKeySecret: doWz4lSLq5n7KxvD9kwWbYfF7KWhnbm2o5kaFw83
  sessionToken: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJQVE4zWFRMRFI5MkJCTk5PTTFCMSIsImV4cCI6MTY4OTA2MjQ2NSwicGFyZW50IjoiY2pqZDJoIiwic2Vzc2lvblBvbGljeSI6ImV5SldaWEp6YVc5dUlqb2lNakF4TWkweE1DMHhOeUlzSWxOMFlYUmxiV1Z1ZENJNlczc2lVMmxrSWpvaVlYQndMWE4wY3kxbWRXeHNMV2R5WVc1MElpd2lSV1ptWldOMElqb2lRV3hzYjNjaUxDSkJZM1JwYjI0aU9pSnpNem9xSWl3aVVtVnpiM1Z5WTJVaU9pSmhjbTQ2WVhkek9uTXpPam82S2lKOVhYMD0ifQ.wD5_ZiCRku9Db1YhpPZAPj4pKB8v8wddU_q8Mch67fQMa7s0oJk9hJZUxvPseGi3a-Mr6LSTjhGY_lw9uflsYg
  expire: 1689062463
